services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env-docker
    command: >
      sh -c "alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000"
    # command: sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "5000:8000"


  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env-docker

volumes:
  postgres_data:

