"""update Event

Revision ID: da9156555eb2
Revises: d80c6abe254f
Create Date: 2025-03-31 12:02:26.257076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9156555eb2'
down_revision: Union[str, None] = 'd80c6abe254f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'event_id')
    # ### end Alembic commands ###
