"""update Post.community_id

Revision ID: e03aa323d44c
Revises: 7ea4a68ccdc4
Create Date: 2025-03-18 15:39:01.085019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03aa323d44c'
down_revision: Union[str, None] = '7ea4a68ccdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
