"""update Post

Revision ID: 28ff4d1ae7d7
Revises: 3a6fc4408c80
Create Date: 2025-03-22 11:43:51.161654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ff4d1ae7d7'
down_revision: Union[str, None] = '3a6fc4408c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
