"""update Post.community_id

Revision ID: 60cd04febf79
Revises: ef06cee910a0
Create Date: 2025-03-18 14:09:10.811247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cd04febf79'
down_revision: Union[str, None] = 'ef06cee910a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'community', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'community_id')
    # ### end Alembic commands ###
