"""update Event

Revision ID: d80c6abe254f
Revises: 178552f09103
Create Date: 2025-03-31 11:51:50.180807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80c6abe254f'
down_revision: Union[str, None] = '178552f09103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_event_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_event_id_fkey', 'post', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
