"""update User

Revision ID: 41b8c282a92f
Revises: 8eee28c635de
Create Date: 2025-03-17 15:21:15.166677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41b8c282a92f"
down_revision: Union[str, None] = "8eee28c635de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("user", sa.Column("is_phone_verified", sa.Boolean(), nullable=True))
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=320), nullable=True
    )
    op.create_unique_constraint(None, "user", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=320), nullable=False
    )
    op.drop_column("user", "is_phone_verified")
    op.drop_column("user", "phone")
    # ### end Alembic commands ###
