"""add Poll

Revision ID: 5c9aa709addf
Revises: 2856276f73fb
Create Date: 2025-04-14 15:47:14.020237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9aa709addf'
down_revision: Union[str, None] = '2856276f73fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_polls', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_polls', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_polls', type_='foreignkey')
    op.drop_column('event_polls', 'user_id')
    # ### end Alembic commands ###
