"""update Event

Revision ID: 974370dc617a
Revises: c08614184384
Create Date: 2025-03-28 16:18:08.067456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974370dc617a'
down_revision: Union[str, None] = 'c08614184384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('event_organizer_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    op.drop_column('event', 'organizer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_organizer_id_fkey', 'event', 'user', ['organizer_id'], ['id'])
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
