"""change Event

Revision ID: fc0b8d97d20d
Revises: 8d7fa11ebfca
Create Date: 2025-04-14 13:43:20.154320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0b8d97d20d'
down_revision: Union[str, None] = '8d7fa11ebfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'max_participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
