"""add WorkoutStatistics

Revision ID: 2dbd63f9fc3d
Revises: 11cfa12c76c7
Create Date: 2025-04-05 14:00:45.833663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbd63f9fc3d'
down_revision: Union[str, None] = '11cfa12c76c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_statistics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('total_duration_sec', sa.Integer(), nullable=False),
    sa.Column('runs_count', sa.Integer(), nullable=False),
    sa.Column('runs_distance', sa.Float(), nullable=False),
    sa.Column('bicycles_count', sa.Integer(), nullable=False),
    sa.Column('bicycles_distance', sa.Float(), nullable=False),
    sa.Column('walks_count', sa.Integer(), nullable=False),
    sa.Column('walks_distance', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_statistics')
    # ### end Alembic commands ###
