"""update Post.community_id

Revision ID: 7ea4a68ccdc4
Revises: 60cd04febf79
Create Date: 2025-03-18 14:42:16.397475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea4a68ccdc4'
down_revision: Union[str, None] = '60cd04febf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
