"""comment

Revision ID: dc8d75cf12d2
Revises: 1f1fc1bdf7dc
Create Date: 2025-03-16 14:02:35.644441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc8d75cf12d2"
down_revision: Union[str, None] = "1f1fc1bdf7dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_comment_id", table_name="comment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_comment_id", "comment", ["id"], unique=False)
    # ### end Alembic commands ###
