"""add OAuthAccount

Revision ID: 0e862a1f9d18
Revises: f53b0b085ee3
Create Date: 2025-04-08 15:07:12.751525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e862a1f9d18'
down_revision: Union[str, None] = 'f53b0b085ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
