"""add WorkoutStatistics

Revision ID: a82dcfa817a3
Revises: 2dbd63f9fc3d
Create Date: 2025-04-05 14:25:34.154074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82dcfa817a3'
down_revision: Union[str, None] = '2dbd63f9fc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workout_statistics', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_statistics', type_='unique')
    # ### end Alembic commands ###
