"""add WorkoutStatistics

Revision ID: f3f0d4785ffe
Revises: 4320f93a8fe5
Create Date: 2025-04-05 14:35:08.626301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f0d4785ffe'
down_revision: Union[str, None] = '4320f93a8fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
