"""Profile

Revision ID: 8eee28c635de
Revises: f6bedc5bee9b
Create Date: 2025-03-17 13:38:04.286981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8eee28c635de"
down_revision: Union[str, None] = "f6bedc5bee9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profile", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profile", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
