"""update Event

Revision ID: ace53a337b79
Revises: a00847f637de
Create Date: 2025-03-28 17:03:55.357177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace53a337b79'
down_revision: Union[str, None] = 'a00847f637de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'end_datetime')
    op.drop_column('event', 'start_datetime')
    # ### end Alembic commands ###
