"""update Message

Revision ID: 3a6fc4408c80
Revises: 03151afcce40
Create Date: 2025-03-21 17:27:56.287066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6fc4408c80'
down_revision: Union[str, None] = '03151afcce40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_sender_id_fkey', 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###
