"""gym

Revision ID: b21cce9c6346
Revises: 43af3fb0e70c
Create Date: 2025-04-04 15:38:07.850158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21cce9c6346'
down_revision: Union[str, None] = '43af3fb0e70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercise', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'user_id')
    # ### end Alembic commands ###
