"""add WorkoutStatistics

Revision ID: f8a4fb5a83cd
Revises: a82dcfa817a3
Create Date: 2025-04-05 14:30:15.169899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a4fb5a83cd'
down_revision: Union[str, None] = 'a82dcfa817a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
