"""gym

Revision ID: 43af3fb0e70c
Revises: 
Create Date: 2025-04-04 15:26:48.070730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43af3fb0e70c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('equipment', sa.Enum('ANY', 'NONE', 'BARBELL', 'DUMBBELLS', 'RESISTANCE_BANDS', 'BENCH', 'KETTLEBELLS', 'WEIGHT_PLATES', 'GYMNASTIC_BALL', 'EZ_BAR', 'PULL_UP_BAR', 'MACHINES', name='equipment'), nullable=False),
    sa.Column('difficulty', sa.Enum('ALL', 'BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('workout_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('muscle_group', sa.Enum('BACK', 'TRICEPS', 'CHEST', 'SHOULDERS', 'CORE', 'BICEPS', 'FOREARM', 'THIGHS', 'GLUTES', 'CALVES', 'FULL_BODY', name='musclegroup'), nullable=False),
    sa.Column('gym_workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gym_workout_id'], ['gym_workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_set')
    op.drop_table('exercise')
    op.drop_table('gym_workout')
    # ### end Alembic commands ###
