"""update Activity

Revision ID: 9d1d312fac1e
Revises: 0db6b568ff97
Create Date: 2025-03-25 17:17:18.416856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1d312fac1e'
down_revision: Union[str, None] = '0db6b568ff97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('map', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'map')
    # ### end Alembic commands ###
