"""add WorkoutStatistics

Revision ID: 6d5f10555328
Revises: 701aeeafdb3d
Create Date: 2025-04-05 14:49:31.463055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5f10555328'
down_revision: Union[str, None] = '701aeeafdb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participation', 'id')
    op.drop_constraint('workout_statistics_user_id_key', 'workout_statistics', type_='unique')
    op.drop_column('workout_statistics', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_statistics', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('workout_statistics_user_id_key', 'workout_statistics', ['user_id'])
    op.add_column('event_participation', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
