"""add WorkoutStatistics

Revision ID: 4320f93a8fe5
Revises: f8a4fb5a83cd
Create Date: 2025-04-05 14:30:43.737440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4320f93a8fe5'
down_revision: Union[str, None] = 'f8a4fb5a83cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
