"""add image_path to Post

Revision ID: 298ce0dbc5fc
Revises: 9899623bb0e6
Create Date: 2025-03-11 14:27:26.881064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298ce0dbc5fc'
down_revision: Union[str, None] = '9899623bb0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_path')
    # ### end Alembic commands ###
