"""update post

Revision ID: 9d38697285f7
Revises: c37bbbe525b2
Create Date: 2025-01-06 15:10:36.302060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d38697285f7'
down_revision: Union[str, None] = 'c37bbbe525b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('post', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
